apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init
data:
  init.sh: |
    #!/bin/bash
    inicia() {
      # Wait for last replica ready
      until mongo mongo-2 --eval 'printjson(db.serverStatus())'; do
        sleep 2
      done
      mongo --eval="printjson(rs.initiate( \
          { \
            '_id' : 'rs0', \
            members: [ \
              { '_id': 0, host: 'mongo-0:27017' }, \
              { '_id': 1, host: 'mongo-1:27017' }, \
              { '_id': 2, host: 'mongo-2:27017' } \
            ] \
          }))"
    }
    if [[ "${HOSTNAME}" == 'mongo-0' ]]; then
      inicia &
    fi    
    mongod --replSet rs0 --bind_ip localhost,${HOSTNAME}
    